#!/bin/bash

path="$(gsettings get org.gnome.desktop.background picture-uri | sed -e "s/^'file:\/\///" -e "s/'$//")"

echo "O wallpaper actual é: $path"

if [ -f "$path" ]; then
    echo "Desexas eliminalo?"
    select confirm in Si Non
    do
        case $confirm in
            Si) 
                if rm -f "$path"; then
                    echo "O ficheiro $path foi eliminado."
                    wlp
                    exit 0
                else
                    echo "Erro eliminando o ficheiro $path"
                    exit 2
                fi
                ;;
            Non)
                echo "Non se procederá co borrado."
                exit 0
                ;;
        esac
    done
else
    echo "O ficheiro $path non existe."
    exit 1
fi
