#!/bin/sh

#
# bl - backlight
#

case $BLOCK_BUTTON in
	4) xbacklight -inc 5 ;;
	5) xbacklight -dec 5 ;;
esac

# Set default laptop's screen name
laptop="eDP1"

# Set default emoji
if fc-list | grep -q "Nerd Font" ; then
    emoji="盛"
else
    emoji="☀️"
fi

get_active_monitors()
{
    xrandr | awk '/\ connected/ && /[[:digit:]]x[[:digit:]].*+/{print $1}'
}

if get_active_monitors | grep -q "$laptop"; then
    bl=$(xbacklight -get)
    echo "$emoji ${bl%.*}%"
else exit 0; fi
