#!/bin/sh
# https://raw.githubusercontent.com/LukeSmithxyz/voidrice/4cb6e5451b40766211e7b7ded243347d55d69153/.scripts/statusbar/i3weather
### This is only if your location isn't automatically detected, otherwise you can leave it blank.
. ~/.config/i3weather
# location=""

case $BLOCK_BUTTON in
    1) alacritty -e w3m es.wttr.in/$location ;;
    # 3) pgrep -x dunst >/dev/null && notify-send "<b>🌈 Weather module:</b>
# - Click for wttr.in forecast.
# ☔: Chance of rain/snow
# ❄: Daily low
# 🌞: Daily high" ;;
esac

[ "$location" != "" ] && location="$location+"

gw=$(ip r | grep default | tail -1 | cut -d ' ' -f 3)

[ -z $gw ] && exit 0

ping -q -w 1 -c 1 "$(ip r | grep default | tail -1 | cut -d ' ' -f 3)" >/dev/null 2>&1 || exit 0

curl -s wttr.in/$location > ~/.cache/weatherreport

printf "%s" "$(sed '16q;d' ~/.cache/weatherreport | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/ /g" | tr -d '\n')"

sed '13q;d' ~/.cache/weatherreport | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " ",$1 "°","盛",$2 "°"}'
